export const GET_MENUDATA_SUCCESS = 'GET_MENUDATA_SUCCESS';
export const WEBSERVERLIST = 'WEBSERVERLIST';
export const DELETE_WEBSERVERLIST = 'DELETE_WEBSERVERLIST';CURRENT_SLB_NAME
export const CURRENT_SLB_NAME = 'CURRENT_SLB_NAME';
export const SET_REFER_SERVER_SUCCESS = 'SET_REFER_SERVER_SUCCESS';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';