export const SHOW_ADD_SLB_MODAL = 'SHOW_ADD_SLB_MODAL'
export const SHOW_ADD_SERVER_MODAL = 'SHOW_ADD_SERVER_MODAL'
export const SHOW_ADD_TG_MODAL = 'SHOW_ADD_TG_MODAL'
export const VALIDATE_DOMAIN_RESULT = 'VALIDATE_DOMAIN_RESULT'

